config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :skip => [:registrations] 
  get '/users/sign_up', to: redirect('/404.html')
  root 'members#index'
  post 'members/update_fee/:id' => 'members#update_fee',:as => 'update_fee'
  
  get 'members/fee_pay/:id' => 'members#fee_pay'
  post 'members/fee_pay_regular/:id' => 'members#fee_pay_regular'
  post 'members/fee_pay_new/:id' => 'members#fee_pay_new'
  post 'members/member_reset/:id' => 'members#member_reset'
  get 'members/reset/:id' => 'members#reset',:as => 'member_date_change'
  
  resources :members do
    collection {get :autocomplete}
    collection {get :upcoming_fee}
    collection {get :pending_fee}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord


def self.check_validation(member)
    if member.last_fee_date != nil && member.next_fee_date
       return false
    else
        return true
    end
end   
    
enum status: [:Unpaid ,:Paid, :Inactive]
    
def self.search(search)
    where('name LIKE ?',"%#{search}%")
end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member, only: [:show, :edit, :update, :destroy,:fee_pay,:fee_pay_regular,:fee_pay_new,:member_reset ,:reset]
  require 'will_paginate/array'
  
  
  # GET /members
  # GET /members.json
  def index
    if params[:search]
      @members = Member.search(params[:search]).paginate(:page => params[:page], :per_page => 15)
    else  
      @members = Member.all.paginate(:page => params[:page],:per_page => 15)
      @members.each do |member|
        if member.next_fee_date != nil   
          if member.next_fee_date < Date.today && member.next_fee_date > (Date.today - 1.month)
          
           member.Unpaid!
          
          elsif member.next_fee_date < (Date.today - 1.month)
           member.Inactive!
          else
           member.Paid!
          end
        else
          member.Unpaid!
        end
        
      end
    end
  end                                    #index function ends
  
  
  
  
  def autocomplete
    @members = Member.order(:name).where('lower(name) LIKE ?',"%#{params[:term]}%".downcase)
    respond_to do |format|
      format.html
      format.json {
        render json: @members.map(&:name).to_json
      }
    end
  end                               #autocomplete function completes
  
  
  
  # GET /members/pending_fee   - pending_fee_members_path
  def pending_fee
    if params[:search]
      @members = Member.search(params[:search]).paginate(:page => params[:page], :per_page => 15)
    else
    @membersall = Member.all
    @memberstotal =[ ]
    @membersall.each do |member|
      if member.next_fee_date != nil 
      if member.next_fee_date < Date.today 
      
          @memberstotal << member
      end
      else
         @memberstotal << member
      end
    end
    @members = @memberstotal.paginate(:page => params[:page], :per_page => 15)
    end
    
  end                              #end of pending_fee function
  
  
  
  # GET /members/upcoming_fee    - upcoming_fee_members_path
  def upcoming_fee
    if params[:search]
      @members = Member.search(params[:search]).paginate(:page => params[:page], :per_page => 15)
    else
    @membersall =Member.all
    @memberstotal = []
    @membersall.each do |member|
      if member.next_fee_date != nil
      if ((member.next_fee_date > Date.today && member.next_fee_date < (Date.today + 4.days)))
        @memberstotal << member
      end
      else
        @memberstotal << member
      end
    end
    @members = @memberstotal.paginate(:page => params[:page],:per_page => 15)
    end
  end                  #end of upcoming fee function
  
 
  def update_fee
    @member = Member.find(params[:id])
    attributes = update_fee_params.clone
    if attributes[:amount] == "600"
        @member.last_fee_date = @member.next_fee_date 
        @member.next_fee_date = @member.next_fee_date + 31.days
    elsif attributes[:amount] == "1500"
        @member.last_fee_date = @member.next_fee_date
        @member.next_fee_date = @member.next_fee_date + 3.month
    end
     respond_to do |format|
      #if @member.update(update_fee_params) 
      if @member.save   
        @member.Paid!
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
        format.js 
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
        format.js 
      end
    end
    
  end                 # end of update_fee

 
 
  # GET /members/1
  # GET /members/1.json
  def show
    if @member.next_fee_date != nil
      if @member.next_fee_date < Date.today && @member.next_fee_date > (Date.today - 1.month)
        
        @member.Unpaid!
      elsif @member.next_fee_date < (Date.today - 1.month) 
        @member.Inactive!
      else
        @member.Paid!
      end
    else
      @member.Unpaid!
    end
    
  end                    #show function end

  
  # GET /members/new
  def new
    @member = Member.new
  end                    # new function end

  
  # GET /members/1/edit
  def edit
  end                    #edit function end
  
  def reset
  end                    #reset function end
  
  def fee_pay
    
  end                     #fee_pay function end
  
 # def fee_pay_regular
#    attributes = fee_regular_params.clone
#    if attributes[:amount] == "400"
#      if @member.last_fee_date != nil &&  @member.next_fee_date != nil 
#      @member.last_fee_date = @member.next_fee_date
#      @member.next_fee_date = @member.next_fee_date + 31.days
#      else
#      @member.last_fee_date = Date.today
#      @member.next_fee_date = Date.today + 31.days
#      end
#    elsif attributes[:amount] == "1000"
#      if @member.last_fee_date != nil && @member.next_fee_date != nil 
#      @member.last_fee_date = @member.next_fee_date
#      @member.next_fee_date = @member.next_fee_date + 3.month
#      else
#      @member.last_fee_date = Date.today
#      @member.next_fee_date = Date.today + 3.month
#      end
#    end
#    respond_to do |format|
#      if @member.update(fee_regular_params) && @member.save
#        @member.Paid!
#        format.html { redirect_to @member, notice: "Member's fee updated successfully." }
#        format.json { render :show, status: :created, location: @member }
#      else
#        format.html { render :fee_pay }
#        flash[:alert] = "There must be some blank field which is not selected ,Please fill the form properly"        
#      end
#    end
#    
#  end
  
  
#   def fee_pay_new
#    @result=Member.check_validation(@member)
#    if @result ==true
#      attributes = fee_regular_params.clone
#      if attributes[:amount] == "600"
#       @member.last_fee_date = @member.admission_date
#        @member.next_fee_date = @member.admission_date + 31.days
#      elsif attributes[:amount] == "1500"
#        @member.last_fee_date = @member.admission_date
#        @member.next_fee_date = @member.admission_date + 3.month
#      end
#      respond_to do |format|
#        if @member.update(fee_regular_params) && @member.save
#          @member.Paid!
#          format.html { redirect_to @member, notice: "Member's fee updated successfully." }
#          format.json { render :show, status: :created, location: @member }
#        else
#          format.html { render :fee_pay }
#          flash[:alert] = "There must be some blank field which is not selected ,Please fill the form again properly"        
#        end
#      end
#    else
#      respond_to do |format|
#        format.html { redirect_to :back }
#        flash[:alert] = "This member is not new, either click on RESET button or the Regular member button and  fill the form"; 
#      end
#    end
#    
#   end
  
  
  def member_reset
     #attributes = member_reset_params.clone
     next_fee_date = Date.new(params[:member]["next_fee_date(1i)"].to_i,params[:member]["next_fee_date(2i)"].to_i,params[:member]["next_fee_date(3i)"].to_i)
  if (next_fee_date < Date.today)
  
         redirect_to(:back)
         flash[:alert] = "Please fill the form properly"
         
  else    
     respond_to do |format|
       
      if @member.update(member_reset_params) 
        format.html { redirect_to @member, notice: "Member's fee and fee dates updated successfully." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { redirect_to(request.env['HTTP_REFERER']) }
        flash[:alert] = "Please fill the form again"
      end
    end
  end
  end
 
 
  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    attributes = member_params.clone
      if attributes[:amount] == "600"
        @member.last_fee_date = @member.admission_date
        @member.next_fee_date = @member.admission_date + 31.days
      elsif attributes[:amount] == "1500"
        @member.last_fee_date = @member.admission_date
        @member.next_fee_date = @member.admission_date + 3.month
      end
    
    respond_to do |format|
      if @member.save
        @member.Paid!
        format.html { render :show, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
  
    respond_to do |format|
      if @member.update(member_params) 
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :admission_date, :status, :amount)
    end
    
    def fee_regular_params
       params.require(:member).permit( :status, :amount)
    end
    
    def update_fee_params
       params.require(:member).permit(:amount)
    end
    
    def member_reset_params
      params.require(:member).permit(:last_fee_date,:next_fee_date,:amount,:status)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<div class="col-xs-6 col-xs-offset-3 form-custom">
<%= simple_form_for @member, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name ,placeholder: "Enter the member's name here"%>
  
  <%= f.input :admission_date %>
  
  <% #f.input :status,disabled: true %>
  
  <%= f.input :amount,as: :radio_buttons,collection: [['600',600],['1500',1500]] %>
  
 
 <hr/>
  <%= f.button :submit, :class => 'btn btn-primary btn-xs' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn btn-default btn-xs' %>
<% end %>
</div>

app/views/members/_form_edit.html.erb
<div class="col-xs-12 form-custom">
<%= simple_form_for @member, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  
  <%= f.input :admission_date %>
  
  <%= f.input :status,disabled: true %>
  
  <%= f.input :amount,as: :radio_buttons,collection: [['600',600],['1500',1500]] %>
  

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn btn-default' %>
<% end %>
</div>

app/views/members/_reset_form.html.erb
<div>
    <hr/>
    <p><strong>Note:</strong>Here You can change the members Last Fee Date and Next Fee Date.</p>
    <p><strong>Note:</strong>Make sure to select the date.</p>
    <div class="row">   
        <div class="col-xs-6 form-custom-reset" >
            <div class="page-header"><h4>Fill the form (Regular Member)</h4></div>
            <%= simple_form_for @member,url: {:controller => 'members',:action => 'member_reset',:id => @member},method: :post, :html => { :class => 'form-horizontal' } do |f| %>
              <%= f.input :last_fee_date ,label: "Set The last fee date ",hint: "You have select the date otherwise today's date will be set" %>
               <%= f.input :next_fee_date ,label: "Set The next fee date ",hint: "You have select the date otherwise today's date will be set" %>
              <%= f.input :status,as: :select,collection: [['Unpaid','Unpaid'],['Paid','Paid']],include_blank: false,prompt: "Please Select Status or it will be automatically set" %>
              <%= f.input :amount,as: :select,collection: [['600',600],['1500',1500]],include_blank: false %>
              
            <hr/>
              <%= f.button :submit, :class => 'btn-primary btn-xs' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                            members_path, :class => 'btn btn-default btn-xs' %>
            <% end %>
        </div>
        <div class="col-xs-4 col-xs-offset-2 form-custom-reset" >
            <div class="page-header">
            <h4>Member Details</h4>
            </div>
            <p><strong>Member Name : </strong><%= @member.name %></p>
            <p><strong>Admission Date : </strong><%= @member.admission_date %></p>
            <p><strong>Last Fee Date: </strong><%= @member.last_fee_date %></p>
            <p><strong>Next Fee Date : </strong><%= @member.next_fee_date %></p>
        </div>
    </div>
</div>   <!--for setting the dates

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/members/index.html.erb
<script type="text/javascript">
$(function(){
  $("#search-member-autocomplete").autocomplete({
    source: '<%= autocomplete_members_path(:json) %>'
  })
})
</script>
<%- model_class = Member -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>
<%= form_tag members_path, :method => 'get' do %>
        
        <div>
        <div >Name of member: </div>
            <div class="row">
            <div class="col-xs-5">
              <%= text_field_tag :search, params[:search],id: 'search-member-autocomplete',class: "form-control" %>
            </div>
            <div class="col-xs-1">
              <%# submit_tag "Search", :name => nil,class: "btn btn-info btn-sm" %>
              <button type="submit"  class="btn btn-info btn-sm" ><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </div>
            
            
       </div>
<% end %>
<hr/>
<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
       <th><%= model_class.human_attribute_name(:admission_date) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%=  member.id %></td>
        <td><%= link_to member.name, member_path(member) %></td>
        <td><%= member.admission_date.strftime("%d-%m-%Y")%></td>
        <% if member.Unpaid? %>
        <td ><span id="button-style-unpaid"><%= member.status %></span></td>
        <% elsif member.Inactive? %>
        <td ><span id="button-style-inactive"><%= member.status %></span></td>
        <% else %>
        <td ><span id="button-style-paid"><%= member.status %></span></td>
        <% end %>
        <td>
          <% if member.next_fee_date != nil %>
          <% if (member.next_fee_date < Date.today && member.next_fee_date > (Date.today - 1.month)) && member.Unpaid? %>
          <%# link_to 'Fee Pay',
                      {:controller => 'members',:action => 'fee_pay',:id => member}, :class => 'btn btn-default btn-xs' %>
          <button type="button" data-toggle="modal" data-id="<%= member.id %>" data-target="#mymodalmember_<%= member.id %>">Update fee</button>
          <% end %>
          <% if  member.next_fee_date < (Date.today - 1.month) %>
          <%# link_to 'Fee Pay',
                      {:controller => 'members',:action => 'fee_pay',:id => member}, :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Reset' ,member_date_change_path(member) ,class: "btn btn-success btn-xs" %>
          <% end %>
          <% else %>
          <%# link_to 'Fee Pay',
                       {:controller => 'members' , :action => 'fee_pay',:id => member} , :class => 'btn btn-default btn-xs' %>
            <button type="button" data-toggle="modal" data-id="<%= member.id %>" data-target="#mymodalmember_<%= member.id %>">Update fee</button>
          <% end %>
          
          <!--<button type="button" data-toggle="modal" data-target="#mymodalmember">Update fee</button>-->
          
        
          
          <%= link_to "Delete",
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      
      <!-- Modal -->
      
<%= simple_form_for(member,:url => {:controller=> 'members',:action => 'update_fee',:id =>member.id},method: :post,remote: true) do |f| %>
<div class="modal fade" id="mymodalmember_<%= member.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Update Member's fee</h4>
      </div>
      <div class="modal-body">
        
        <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        
      <% end %>
      </ul>
      
    </div>
  		<% end %>
  		
  	<div id="errordiv" style="display:none;color:red;">Please select the amount</div>
  	<br/>
	  <div class="field">
	     <%= f.label :amount ,"Amount" %>
	     <%= f.input :amount,label: false,as: :radio_buttons , collection: [["600",600],["1500",1500]] %>
	     <!--<p><input id="member_amount_600" name="member[amount]" type="radio" value="600" />
	     <label class="collection_radio_buttons" for="member_amount_600">600</label></p>
	     <p><input id="member_amount_1500" name="member[amount]" type="radio" value="1500" />
	     <label class="collection_radio_buttons" for="member_amount_1500">1500</label></p>-->
	  </div>
	  
      </div>                 <!-- end of modal body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="myModalponyclose" data-dismiss="modal">Close</button>
        <%= f.button :submit,  "Save Changes" ,class: 'btn btn-primary btn-sm' %>
        <% end %>               <!-- end of simple-form -->
      </div>
    </div>
  </div>
</div>


<% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>
<hr/>
<div>
  <% if @members != nil %>
  <%= will_paginate @memebers %>
  <% end%>
</div>


<script>
$(document).ready(function() {
      
      
     $('.edit_member').submit(function(){
       if(document.getElementById('member_amount_600').checked == false && document.getElementById('member_amount_1500').checked == false)
       {
        // document.getElementById('errordiv').innerHTML = 'Please select the amount';
         $('#errordiv').show();
         return false;
       }
       else
       {
         return true; 
       }
      
       
     });
     
      $('#mymodalmember').on('hidden.bs.modal', function(){
            $(this).find('form').trigger('reset');
            $('#errordiv').hide();
      });
     /*$('#ci').click(function(){
       alert("hi");
      // $('#ci').text = "kiran";
        
    
     if(document.getElementById('member_amount_600').checked) {
          alert('Check 600');
   }else if(document.getElementById('member_amount_1500').checked) {
  //Female radio button is checked
    }
     });*/
});
</script>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="text-center">
  <h3><strong><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></strong></h3>
</div>
<%= render :partial => 'form' %>

app/views/members/pending_fee.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h3>Pending Fees</h3>
</div>
<%= form_tag pending_fee_members_path, :method => 'get' do %>
        
        <div>
        <div >Name of member: </div>
          <div class="row">
            <div class="col-xs-5">
              <%= text_field_tag :search, params[:search],id: 'search-member-autocomplete',class: "form-control" %>
            </div>
            <div class="col-xs-1">
              <%# submit_tag "Search", :name => nil,class: "btn btn-info btn-sm" %>
            <button type="submit"  class="btn btn-info btn-sm" ><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </div>
            
            
       </div>
<% end %>
<hr/>
<table class="table table-responsive table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:next_fee_date) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  
<% if @members.blank? %>
  <p>There are no members with pending fee.</p>
<% else %>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        
        <td><%= link_to member.name, member_path(member) %></td>
        <% if member.next_fee_date != nil %>
        <td><%=link_to member.next_fee_date.strftime("%d-%m-%Y"), member_date_change_path(member)%></td>
        <% else %>
        <td></td>
        <% end %>
        <% if member.Unpaid? %>
        <td ><span id="button-style-unpaid"><%= member.status %></span></td>
        <% else %>
        <td ><span id="button-style-paid"><%= member.status %></span></td>
        <% end %>
        <td>
          <% if member.next_fee_date != nil %>
          <% if (member.next_fee_date < Date.today && member.next_fee_date > (Date.today - 1.month)) && member.Unpaid? %>
          <button type="button" data-toggle="modal" data-id="<%= member.id %>" data-target="#mymodalmember_<%= member.id %>">Update fee</button>
          <%# link_to 'Fee Pay',
                       {:controller => 'members' , :action => 'fee_pay',:id => member} , :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if  member.next_fee_date < (Date.today - 1.month) %>
          <%# link_to 'Fee Pay',
                      {:controller => 'members',:action => 'fee_pay',:id => member}, :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Reset' ,member_date_change_path(member) ,class: "btn btn-success btn-xs" %>
          <% end %>
          <% else %>
          <button type="button" data-toggle="modal" data-id="<%= member.id %>" data-target="#mymodalmember_<%= member.id %>">Update fee</button>
          <%# link_to 'Fee Pay',
                       {:controller => 'members' , :action => 'fee_pay',:id => member} , :class => 'btn btn-default btn-xs' %>
          <% end %>
         
         
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <!-- Modal -->
      
<%= simple_form_for(member,:url => {:controller=> 'members',:action => 'update_fee',:id =>member.id},method: :post,remote: true) do |f| %>
<div class="modal fade" id="mymodalmember_<%= member.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Update Member's fee</h4>
      </div>
      <div class="modal-body">
        
        <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        
      <% end %>
      </ul>
      
    </div>
  		<% end %>
  		
  	<div id="errordiv" style="display:none;color:red;">Please select the amount</div>
  	<br/>
	  <div class="field">
	     <%= f.label :amount ,"Amount" %>
	     <%= f.input :amount,label: false,as: :radio_buttons , collection: [["600",600],["1500",1500]] %>
	     <!--<p><input id="member_amount_600" name="member[amount]" type="radio" value="600" />
	     <label class="collection_radio_buttons" for="member_amount_600">600</label></p>
	     <p><input id="member_amount_1500" name="member[amount]" type="radio" value="1500" />
	     <label class="collection_radio_buttons" for="member_amount_1500">1500</label></p>-->
	  </div>
	  
      </div>                 <!-- end of modal body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="myModalponyclose" data-dismiss="modal">Close</button>
        <%= f.button :submit,  "Save Changes" ,class: 'btn btn-primary btn-sm' %>
        <% end %>               <!-- end of simple-form -->
      </div>
    </div>
  </div>
</div>                      <!-- end of modal-->        
      
    <% end %>
  </tbody>
<% end%>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>
            
<hr/>
<div>
  <% if @members != nil %>
  <%= will_paginate @memebers %>
  <% end%>
</div>

<script>
$(document).ready(function() {
      
      
     $('.edit_member').submit(function(){
       if(document.getElementById('member_amount_600').checked == false && document.getElementById('member_amount_1500').checked == false)
       {
        // document.getElementById('errordiv').innerHTML = 'Please select the amount';
         $('#errordiv').show();
         return false;
       }
       else
       {
         return true; 
       }
      
       
     });
     
      $('#mymodalmember').on('hidden.bs.modal', function(){
            $(this).find('form').trigger('reset');
            $('#errordiv').hide();
      });
     /*$('#ci').click(function(){
       alert("hi");
      // $('#ci').text = "kiran";
        
    
     if(document.getElementById('member_amount_600').checked) {
          alert('Check 600');
   }else if(document.getElementById('member_amount_1500').checked) {
  //Female radio button is checked
    }
     });*/
});
</script>

app/views/members/reset.html.erb
<%- model_class = Member -%>
<div class="">
  <h3>Reset Members fee dates</h3>
</div>
<%= render :partial => 'reset_form' %>

app/views/members/update_fee.js.erb
alert('Member Updated successfully');
$('#mymodalmember_<%=@member.id %>').modal('hide');
window.location.reload();